### ISSUE TITLE
Peptide identification for BioID samples

### ISSUE THREAD

**Issue by ttessie2** [MSGFPlus/msgfplus#101]
I have data from some BioID experiments and I am wondering about adding biotin as a variable modification. Is the necessary? Will it improve identification?

**Comment by alchemistmatt** [comment]
People run MS-GF+ with a wide variety of dynamic modifications.  If you suspect that some of your peptides are biotinylated, then yes, by all means, run MS-GF+ with a dynamic Biotin mod.  I'm not a biologist or an organic chemist, so you'll have to think carefully about which elements are removed, then added, when your samples get biotinylated.  

I checked some of our parameter files, and I didn't find any where we used Biotin as a standalone dynamic mod.  Note: browse for mod masses at http://www.unimod.org/login.php?message=expired (click "Login as guest").  Biotinylation is +226.077598, but you're better off using the empirical formula.  If you do think a residue can simply gain a biotin molecule (by replacing a hydrogen atom), you'd use this (assuming your target residue is methioine)
```
DynamicMod=C10H14N2O2S, M, opt, any,                Biotin             # Biotinylated methionine
```

**Comment by ttessie2** [comment]
Based on the nature of the experiment only lysine residues will be tagged with biotin. 
Forgive me I am new to this.
Will I have to set up a modification file and call -mod <file>?
If so, could I take the "MSGFPlus_Tryp_NoMods_20ppmParTol.txt" file that is provided in the software documentation and add:
 O1,                  M,  opt, any,               Oxidation       # Oxidation M variable
C10H14N2O2S, K, opt, any,                Biotin             # Biotinylated methionine

Alternatively, would widening the precursor mass tolerance work?

**Comment by alchemistmatt** [comment]
Yes, you could take MSGFPlus_Tryp_NoMods_20ppmParTol.txt and customize it.  To see example parameter files, see https://github.com/MSGFPlus/msgfplus/tree/master/docs/ParameterFiles
Please read the documentation at https://msgfplus.github.io/msgfplus/

You tell MS-GF+ the parameter file to use using -conf and not -mod
For example
```
java -Xmx3500M -jar MSGFPlus.jar -s Dataset.mzML -conf MSGFPlus_Tryp_LysBiotin_MetOx_20ppmParTol.txt 
```

**Comment by ttessie2** [comment]
Thanks, I have it working. Much appreciated!
