### ISSUE TITLE
Question regarding running MSGF+ on all .mzML files in folder

### ISSUE THREAD

**Issue by ttessie2** [MSGFPlus/msgfplus#102]
I've been messing around trying to run MSGF on all .mzML files in a given folder. I only know some basic windows command line as well as python. 
If I run the command line code with -s <path\*.mzML> I get:
[Error] The number of parameters must be even. If a file path has a space, surround it with double quotes.
Any help or direction would be great!

**Comment by alchemistmatt** [comment]
This should work:
```
java -Xmx3500M -jar MSGFPlus.jar -s *.mzML -d YourDatabase.fasta -conf MSGFPlus_PartTryp_MetOx_20ppmParTol.txt
```

See also https://msgfplus.github.io/msgfplus/MSGFPlus.html and browse example parameter file at https://github.com/MSGFPlus/msgfplus/tree/master/docs/ParameterFiles

The parameter files and the -conf switch are easier to use than this
```
java -Xmx3500M -jar MSGFPlus.jar -s Dataset.mzML -d IPI_human_3.79.fasta -inst 1 -t 20ppm -ti -1,2 -ntt 2 -tda 1
```

**Comment by ttessie2** [comment]
This is my full command line code that doesn't work:
java -Xmx3500M -jar MSGFPlus.jar -s C:\path\to\directory\*.mzML -d C:\path\to\fastafile\ -decoy DECOY -conf C:\path\to\conf\MSGFPlus_Tryp_DynMetOx_DynAcetylK_DynBiotinK_20ppmParTol.txt
If I provide the full path to the .mzML file without the wildcard (*) everything works fine. If I use the wildcard I get the error I previously mentioned. The path file doesn't have any space issues. What does the "number of parameters must even" refer to?

**Comment by FarmGeek4Life** [comment]
The problem is that MS-GF+ does not support wildcards in the spectrum file path (as far as I can tell). You can supply the path to a supported file, or you can supply the path to a directory containing supported files. For a directory, it will get the list of files/directories in the directory, and process each file that ends with one of the supported file suffixes (.mgf, .mzxml, .mzml, .ms2, .pkl, .mzdata, _dta.txt).

**Comment by FarmGeek4Life** [comment]
So, instead what you should try is:
```
java -Xmx3500M -jar MSGFPlus.jar -s C:\path\to\directory -d C:\path\to\fastafile\ -decoy DECOY -conf C:\path\to\conf\MSGFPlus_Tryp_DynMetOx_DynAcetylK_DynBiotinK_20ppmParTol.txt
```

**Comment by alchemistmatt** [comment]
```
java -Xmx3500M -jar MSGFPlus.jar -s C:\path\to\directory*.mzML 
```

Is invalid syntax; it should be
```
java -Xmx3500M -jar MSGFPlus.jar -s C:\path\to\directory\*.mzML 
```

But, as pointed out in a previous response, that won't work. You instead must point to a directory.  We need to update the code to support a wildcard filename syntax.  We also need to update https://msgfplus.github.io/msgfplus/MSGFPlus.html to include an example with `-conf`
