### ISSUE TITLE
Is "ScoringParamGen" required?

### ISSUE THREAD

**Issue by jian0104** [MSGFPlus/msgfplus#116]
Hi all,
I just installed MSGFPlus_v20200805 on my windows PC. I generated an mzXML file from a single protein digested .raw file. The peptide searching is fine using other software, so there should be no problem with the mzXML and fasta files. I put the files in specific dir and use 
"C:\Program Files (x86)\Java\jre1.8.0_241\bin\java.exe" -Xmx2000M -jar xxxxxxxxxxx\MSGFPlus_v20200805\MSGFPlus.jar -s C:\Data\MSGF_Plusfiles\xxxxxxx_tryChrLysN.mzXML -o C:\Data\MSGF_Plusfiles\xxxxxxx.mzid -d C:\Data\MSGF_Plusfiles\xxxxxxx.fasta  -t 10ppm -m 0 -inst 1 -e 1 -ti -1,2 -ntt 2 -tda 1 -minLength 4 -maxLength 50 -n 1 -thread 7 -mod xxxxxxxx\MSGFPlus_v20200805\MSGFPlus_Mods1.txt
in command line in windows. File names and directories are hided by "XXXXX" above.
The result shows :
**Skip spectrum scan=8 since it is not centroided
Skip spectrum scan=9 since it is not centroided
Skip spectrum scan=12 since it is not centroided
Skip spectrum scan=13 since it is not centroided
Skip spectrum scan=14 since it is not centroided
Skip spectrum scan=15 since it is not centroided
Skip spectrum scan=16 since it is not centroided
 ...
Ignoring 24432 profile spectra.
Ignoring 0 spectra having less than 10 peaks.
[Error] xxxxxxxx.mzXML does not have any valid spectra**

What can be wrong. I know that the parameters maybe not perfact, but it should at least give me something.
I find this https://msgfplus.github.io/msgfplus/ScoringParamGen.html and wonder if it is required to generate this parameter file and how I use it? I can't find "params" directory in the MSGFPlus_v20200805 folder. Can this cause the problem?

Or if there are some example mzXML file, fasta file that I can use for trouble shooting?

Thank you very much.

**Comment by alchemistmatt** [comment]
MS-GF+ requires centroided spectra (peaks as vertical sticks when a mass spectrum is viewed graphically).
As mentioned in Issue #115, you should use msconvert (from [Proteowizard](http://proteowizard.sourceforge.net/download.html)) to create .mzML files, enabling peak picking.
```
msconvert.exe --32 --mzML --zlib --filter "peakPicking true 1-" *.raw
```

There is also a GUI version of that tool (MSConvertGUI.exe) where you can select the "Peak Picking" filter, use the defaults of "Vendor"and MS Levels 1-, then click "Add" to add the peak picking filter to the filter list.

Note that I suggest you use .mzML files instead of .mzXML, since .mzML files have wider support.

**Comment by alchemistmatt** [comment]
The parameter files are in the zip file in the ParameterFiles subdirectory below the Docs subdirectory.  You can also see them at at https://github.com/MSGFPlus/msgfplus/tree/master/docs/ParameterFiles

As shown at https://msgfplus.github.io/msgfplus/MSGFPlus.html , the suggested way to run MS-GF+ is like this:
```
java -Xmx3500M -jar MSGFPlus.jar -s Dataset.mzML -d ProteinList.fasta -conf MSGFPlus_PartTryp_MetOx_20ppmParTol.txt
```

**Comment by jian0104** [comment]
Thank you very much. I used GUI tool of MSconvert, but didn't realize "Peak Picking" filter. I fixed this and it worked.
