### ISSUE TITLE
Questions about understanding the results

### ISSUE THREAD

**Issue by Wang-kaifei** [MSGFPlus/msgfplus#118]
Hi,

Recently, I ran MS-GF+ and got the .mzid result and converted it to .tsv format.
In the 'protein' column, there is **only one protein** in each row. I would like to ask how to get the sameset of this protein?

Best,
--Kaifei Wang

**Comment by alchemistmatt** [comment]
You should use the [MzidToTsvConverter](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/blob/master/Readme.md) to convert .mzid files to .tsv.  Download a .zip file with the program from here:
* https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/releases

When converting, you have three options, illustrated in batch file [Convert_mzid.bat](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/blob/master/Data/Convert_mzid.bat)
* Option 1: do not unroll proteins: only the first protein for each PSM will be shown
  * This is the default behavior
  * For example output, see row 51 in file [QC_Mam_19_01_1a_25Feb21_Rage_Rep-21-01-02_msgfplus_excerpt.tsv](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/blob/master/Data/QC_Mam_19_01_1a_25Feb21_Rage_Rep-21-01-02_msgfplus_excerpt.tsv)
* Option 2: unroll proteins: for PSMs with multiple proteins, write one line per protein
  * Use `-unroll` to instruct the program to do this
  * For example output, see rows 51, 52, and 53 in file [QC_Mam_19_01_1a_25Feb21_Rage_Rep-21-01-02_unrolled_msgfplus_excerpt.tsv](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/blob/master/Data/QC_Mam_19_01_1a_25Feb21_Rage_Rep-21-01-02_unrolled_msgfplus_excerpt.tsv)
  * Rows 51, 52, and 53 are nearly identical; the only thing that changes is the protein name
* Option 3: for PSMs with multiple proteins, combine protein names into a comma separated list
  * Use `-proteinList` to do this
  * For example output, see row 51 in file [QC_Mam_19_01_1a_25Feb21_Rage_Rep-21-01-02_delimited_msgfplus_excerpt.tsv](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/blob/master/Data/QC_Mam_19_01_1a_25Feb21_Rage_Rep-21-01-02_delimited_msgfplus_excerpt.tsv)
  * Row 51 has `TBB4A_MOUSE, TBB4B_MOUSE, TBB5_MOUSE`

**Comment by Wang-kaifei** [comment]
I'm surprised that you will provide this feature soon ! ! !  The updated version is very easy to use, thank you very much for your help.

**Comment by Wang-kaifei** [comment]
I am surprised that you provide this feature soon ! ! ! The updated version is very easy to use, thank you very much for your help.
