### ISSUE TITLE
Error when writing results: java.lang.ArrayIndexOutOfBoundsException: -8 

### ISSUE THREAD

**Issue by nattzy94** [MSGFPlus/msgfplus#124]
**Describe the bug**
I am searching my spectra against target and decoy peptide files (`orthoalltime.target.fa` and `orthoalltime.decoy.fa`) separately using the following command:
```
for peptides in target decoy; do 
/home/svu/e0470749/jre1.8.0_241/bin/java -Xmx40g -jar ../MSGFPlus_v20210322/MSGFPlus.jar -s ../data/20210509_TY_DukeNUS_SEP_Solution_TEAB.mgf -d orthoalltime.$peptides.fa -o TEAB.orthoalltime.msgf/msgf.$peptides.mzid -t 50ppm -tda 0 -m 1 -inst 1 -e 1 -minLength 5 -maxLength 50 -ignoreMetCleavage 1 -mod msgf-mods.txt -ti 0,0 -thread 12; 
done
```

MSGF+ performs the search for target peptides correctly and I get the output files. However, when it comes to the decoy peptide search, it runs into an error when writing the results. The error I get is: 
```
/home/svu/e0470749/jre1.8.0_241/bin/java -Xmx40g -jar ../MSGFPlus_v20210322/MSGFPlus.jar -s ../data/20210509_TY_DukeNUS_SEP_Solution_TEAB.mgf -d orthoalltime.decoy.fa -o TEAB.orthoalltime.msgf/msgf.decoy.mzid -t 50ppm -tda 0 -m 1 -inst 1 -e 1 -minLength 5 -maxLength 50 -ignoreMetCleavage 1 -mod msgf-mods.txt -ti 0,0 -thread 12
java.lang.ArrayIndexOutOfBoundsException: -8
        at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.getSubsequence(CompactFastaSequence.java:268)
        at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.getMatchingEntry(CompactFastaSequence.java:334)
        at edu.ucsd.msjava.mzid.MZIdentMLGen.getDBSequence(MZIdentMLGen.java:712)
        at edu.ucsd.msjava.mzid.MZIdentMLGen.getPeptideEvidenceList(MZIdentMLGen.java:662)
        at edu.ucsd.msjava.mzid.MZIdentMLGen.addSpectrumIdentificationResults(MZIdentMLGen.java:372)
        at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:454)
        at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:113)
        at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:61)
```
These are the last few lines of the log file of the decoy search:
```
Search progress: 27 / 36 tasks, 96.28%          7.00 minutes elapsed
Search progress: 28 / 36 tasks, 98.15%          7.94 minutes elapsed
Search progress: 28 / 36 tasks, 98.26%          8.00 minutes elapsed
Search progress: 29 / 36 tasks, 98.60%          8.10 minutes elapsed
Search progress: 30 / 36 tasks, 99.00%          8.25 minutes elapsed
Search progress: 31 / 36 tasks, 99.17%          8.27 minutes elapsed
Search progress: 32 / 36 tasks, 99.32%          8.27 minutes elapsed
Search progress: 33 / 36 tasks, 99.46%          8.27 minutes elapsed
Search progress: 34 / 36 tasks, 99.64%          8.29 minutes elapsed
Search progress: 35 / 36 tasks, 99.82%          8.31 minutes elapsed
Search progress: 36 / 36 tasks, 100.00%         8.32 minutes elapsed
Search progress: 36 / 36 tasks, 100.00%         8.32 minutes elapsed
Writing results...
```

`java -version` produces:
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

This is the resource usage report for the cluster job:
```
======================================================================================
      Resource Usage on 2021-07-05 10:21:04.985361:
      JobId: 3092671.venus01                             Project: _pbs_project_default
      Submission Host: atlas8-c01.hpc.local
      Exit Status: 255
      NCPUs Requested: 12                                NCPUs Used: 12
      Memory Requested: 40gb                             Memory Used: 32654252kb
      Vmem Used: 46415776kb
      CPU Time Used: 01:07:51
      Walltime requested: 240:00:00                      Walltime Used: 00:15:24
      Submit Time:  Mon Jul  5 10:05:39 2021             Start Time: Mon Jul  5 10:05:39 2021
      End Time: Mon Jul  5 10:21:04 2021
      Execution Nodes Used: (tiger2-c74:mem=41943040kb:ncpus=12:ngpus=0)
      ======================================================================================
```

Could it be an issue with the memory? I find it strange since it can work with the target peptides but not with the decoy.

**Comment by alchemistmatt** [comment]
I suspect that your FASTA file is too big.  MS-GF+ is a 64-bit program, but references to the FASTA file are limited to 32-bit numbers.  How big is your FASTA file?

**Comment by nattzy94** [comment]
Indeed, the fasta file size is large. The size of both target and decoy fasta files is 8.4G. 
However, I find it odd since the program was able to complete the output for the target database. It only runs into issues with the decoy.

**Comment by javanOkendo** [comment]
did you set td=1 ? double check that with the decoy run parameters

**Comment by nattzy94** [comment]
@javanOkendo I set `-tda 0` for both searches.

**Comment by javanOkendo** [comment]
I think for the decoy database -tda=1. I had this problem before and I used
-tda=1 and it worked. Can you give it a try? Let us know how it goes

**Comment by alchemistmatt** [comment]
Your FASTA file is too large.  As described in issue https://github.com/MSGFPlus/msgfplus/issues/10#issuecomment-428077036 you need to split your FASTA file into separate files, run MS-GF+ against each file, then merge the results.  Use the FASTA File Splitter tool to split the FASTA file, then use the MzIdMerger tool to merge the results:
* https://github.com/PNNL-Comp-Mass-Spec/Fasta-File-Splitter/releases/
* https://github.com/PNNL-Comp-Mass-Spec/MzidMerger/releases

Regarding `-tda` , I suggest you use `-tda 1` which instructs MS-GF+ to create a decoy FASTA file, which includes both forward and reverse sequences.  For more information, go to https://msgfplus.github.io/msgfplus/MSGFPlus.html and search for "automatically creates"
