### ISSUE TITLE
MSGF+ parameter for mass spectra m/z bin width

### ISSUE THREAD

**Issue by nattzy94** [MSGFPlus/msgfplus#125]
Hi,

I would like to use msgf+ using a large mz-bin-width. In search engines such as tide-search or comet, there is a parameter to control the spectral bin width. In tide-search it is the mz-bin-width and in comet there is the fragment_bin_tol parameter. I've looked through the parameters list but cannot find anything resembling this parameter. Wondering if there is an equivalent for msgfplus.

thanks!

**Comment by alchemistmatt** [comment]
MS-GF+ does not allow for specifying the bin width.  The bin width is associated with the trained model defined for each instrument type.  For a large m/z bin width, use `-inst 0` at the command line, or `InstrumentID=1` in a parameter file.  See also:
* https://msgfplus.github.io/msgfplus/MSGFPlus.html
* https://github.com/MSGFPlus/msgfplus/blob/master/docs/ParameterFiles/MSGFPlus_Tryp_MetOx_15ppmParTol.txt#L23
