### ISSUE TITLE
search progress stopped at 79.62% using MSGF+

### ISSUE THREAD

**Issue by MAlinkous** [MSGFPlus/msgfplus#127]
Hi,
    I'm running MSGF+ on a dataset, it worked well in all other mzML files but one with wierd error information: 
`Invalid ErrorScore: 2147483647`, and search progress just stopped  at 79.62%. by the way, I also tried X!Tandem on this files, and it worked.

I have no idea about this error, can you help me with this?

Thanks!

all of the output is:

`MS-GF+ Release (v2019.07.03) (03 July 2019)
Java 1.8.0_252 (Oracle Corporation)
Linux (amd64, version 3.10.0-1062.el7.x86_64)
Loading database files...
Loading database finished (elapsed time: 4.84 sec)
Reading spectra...
Ignoring 0 profile spectra.
Ignoring 0 spectra having less than 10 peaks.
Reading spectra finished (elapsed time: 228.74 sec)
Using 4 threads.
Search Parameters:
	PrecursorMassTolerance: 5.0 ppm
	IsotopeError: -1,2
	TargetDecoyAnalysis: true
	FragmentationMethod: HCD
	Instrument: QExactive (Q-Exactive)
	Enzyme: Tryp
	Protocol: Standard
	NumTolerableTermini: 2
	MinPepLength: 6
	MaxPepLength: 50
	MinCharge: 2
	MaxCharge: 3
	NumMatchesPerSpec: 1
	MaxMissedCleavages: 2
	MaxNumModsPerPeptide: 3
	ChargeCarrierMass: 1.00727649 (proton)
	MinNumPeaksPerSpectrum: 10
	NumIsoforms: 128
Post translational modifications in use:
	Fixed (static):     Carbamidomethyl on C (+57.0215)
	Variable (dynamic): Oxidation on M (+15.9949)
	Variable (dynamic): Acetyl on * at the protein N-terminus (+42.0106)

Spectrum 0-25209 (total: 25210)
Splitting work into 12 tasks.
Search progress: 0 / 12 tasks, 0.00%		0.00 seconds elapsed
Loading built-in param file: HCD_QExactive_Tryp.param
Search progress: 0 / 12 tasks, 27.79%		1.00 minutes elapsed
Search progress: 0 / 12 tasks, 30.09%		2.00 minutes elapsed
Search progress: 1 / 12 tasks, 31.54%		2.47 minutes elapsed
Search progress: 1 / 12 tasks, 23.84%		2.53 minutes elapsed
Search progress: 3 / 12 tasks, 33.29%		2.62 minutes elapsed
Search progress: 3 / 12 tasks, 32.48%		2.73 minutes elapsed
Search progress: 4 / 12 tasks, 56.84%		3.00 minutes elapsed
Search progress: 4 / 12 tasks, 61.98%		4.00 minutes elapsed
Search progress: 4 / 12 tasks, 63.50%		5.00 minutes elapsed
Search progress: 4 / 12 tasks, 55.88%		5.18 minutes elapsed
Search progress: 6 / 12 tasks, 71.98%		5.67 minutes elapsed
Search progress: 6 / 12 tasks, 77.52%		6.00 minutes elapsed
Search progress: 7 / 12 tasks, 79.62%		6.07 minutes elapsed
`

**Comment by alchemistmatt** [comment]
2147483647 is the maximum value for a 32-bit integer, indicating an overflow.  The only way that we could diagnose this would be if you sent us the mzML file and the FASTA file.  But, before we try that, please download the latest release of MS-GF+ from https://github.com/MSGFPlus/msgfplus/releases/

**Comment by MAlinkous** [comment]
I've tried the latest release of MSGF+ and the same error was reported again, and this is the mzML file and FASTA file：https://drive.google.com/file/d/1W0DST3qt03FytueD5fCu7xRz_1mzI1eQ/view?usp=sharing

Thanks!

**Comment by alchemistmatt** [comment]
Thank you for providing the input files.  I was able to reproduce the bug.  When building the scoring graph, several of the edges had scores outside the expected range, and the code would thus abort the search.  Commit 4fa1ed95324b462362fb677082ce34813eff1dde changes this to show a warning, but continue searching.  

For an updated version, see Release 2021.09.06 at https://github.com/MSGFPlus/msgfplus/releases

**Comment by MAlinkous** [comment]
Thanks for your help, and it worked!
