### ISSUE TITLE
Combining identification results of fractions

### ISSUE THREAD

**Issue by rkimoakbioinformatics** [MSGFPlus/msgfplus#130]
**Describe the question or problem**

Each dataset of a CPTAC study has multiple mzML files for multiple "fractions". MS-GF+ runs with each of those mzML files. How should I combine MS-GF+ results to get the peptide identification result for the whole dataset?

**Details**

For example, https://cptac-data-portal.georgetown.edu/study-summary/S038  01CPTAC_OVprospective_Proteome_JHU_20161209 dataset has 24 mzML files from 24 fractions. 24 MS-GF+ runs with each of the 24 mzML files produce 24 MS-GF+ result files. I don't know how to go from here to make a peptide identification result file at a dataset level.

**Useful extras**

Thanks for all the help you have been giving.

**Comment by alchemistmatt** [comment]
Note: the MS-GF+ results are in .mzid files.  In contrast, the .mzML files are XML forms of the original mass spectra.

I can think of two options for combining the MS-GF+ results:

Option 1: Combine the .mzid files using the [MzIdMerger](https://github.com/PNNL-Comp-Mass-Spec/MzidMerger).  Download from the [Releases Page](https://github.com/PNNL-Comp-Mass-Spec/MzidMerger/releases) 
- This would give you a single, combined .mzid file

Option 2: Convert each .mzid file to a .tsv file, optionally filtering while you convert each one.  
- For the conversion, use the [MzidToTsvConverter](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter), available on its [Releases Page](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/releases/tag/v1.4.6) .  
- Optionally use switch `-maxEValue` to filter
- Next, combine them with commands like this:
```
type Dataset1.tsv >> Combined.tsv
type Dataset2.tsv >> Combined.tsv
type Dataset3.tsv >> Combined.tsv
```
Note that these commands are easily generated in Excel or Google Sheets using simple text manipulation formulas, e.g.:
| Row/Col | A | B | 
|----------|----|----|
| 1 | Dataset1.tsv | ="Type " & A1 & " >> Combined.tsv" |
| 2 | Dataset2.tsv | ="Type " & B1 & " >> Combined.tsv" |
| 3 | Dataset3.tsv | ="Type " & C1 & " >> Combined.tsv" |

Use Fill Down to easily populate a series of rows with that formula.

If you go with Option 1, you could still use the  [MzidToTsvConverter](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter) to convert to tab-delimited text.

**Comment by rkimoakbioinformatics** [comment]
@alchemistmatt Thank you. My ultimate goal is to have one _PlusSICStats.txt file from the 24 mzML files. To do this, using the idea of Option 2 and your tools, would the following process be reasonable?

1. Process the 24 mzML files of the 24 fractions of the same dataset with MS-GF+.
2. Make 24 .tsv files with MzidToTsvConverter.
3. Process the 24 mzML files with MASIC.
4. Merge the MS-GF+ and MASIC result files into 24 _PlusSICStats.txt files.
5. In each _PlusSICStats.txt file, normalize peptide abundance with the first reporter ion value (which is "pooled sample").
6. Combine the 24 .tsv files into one .tsv file.
7. Deduplicate peptides in the combined tsv file by removing redundant lines.
8. For each identified peptide in the combined tsv file, find the peptide abundance values for this peptide in the 24 normalized _PlusSICStats.txt files and add them to get the total abundance value for the peptide.
9. After 8, I'll have a file which has a list of unique peptides and their abundance from the 24 fractions.

**Comment by rkimoakbioinformatics** [comment]
@alchemistmatt Thanks! Regarding another question I posted, I figured out.
