### ISSUE TITLE
number of peaks per spectrum

### ISSUE THREAD

**Issue by ypriverol** [MSGFPlus/msgfplus#152]
Hi @alchemistmatt : 

We are using msgf+ in combination with other search engines like comet and SAGE and I just saw that those search engines have a filter for the number of peaks in the spectrum, comet = 10, sage = 15. Im wondering if this could be possible to be implemented in msgf+ or if is already possible to filter based in number of peaks. 

Regards 
Yasset

**Comment by alchemistmatt** [comment]
This option is supported, but only if you use a parameter file
(using the `-conf` switch, as described at https://msgfplus.github.io/msgfplus/MSGFPlus.html)

Browse parameter files at:
https://github.com/MSGFPlus/msgfplus/blob/master/docs/ParameterFiles/

Example parameter file with this option (though it's currently commented out using `#`):
[MSGFPlus_PartTryp_MetOx_20ppmParTol.txt](https://github.com/MSGFPlus/msgfplus/blob/master/docs/ParameterFiles/MSGFPlus_PartTryp_MetOx_20ppmParTol.txt#L87)

**Comment by ypriverol** [comment]
@alchemistmatt do you think would be possible to implement this in the command-line, I could try to do a PR?

**Comment by FarmGeek4Life** [comment]
The parameter is technically usable from the command line, with "-minNumPeaks n", but it's hidden from all of the help documentation.

https://github.com/MSGFPlus/msgfplus/blob/master/src/main/java/edu/ucsd/msjava/params/ParamManager.java
See lines 112, 708, and 803

________________________________

**Comment by ypriverol** [comment]
Yes. Actually, I was checking the code now and in fact all the parameters can be used from the code ;) I was actually reading that line now. Thanks a lot. 

I will test that line now: 

`-minNumPeaks 15`

**Comment by ypriverol** [comment]
I will close the issue ;)

**Comment by alchemistmatt** [comment]
I updated the documentation to mention `-minNumPeaks`
https://msgfplus.github.io/msgfplus/MSGFPlus.html
