### ISSUE TITLE
Why trypsin cleave C-term of methionine?

### ISSUE THREAD

**Issue by bangjiehan** [MSGFPlus/msgfplus#16]
I find some strange results when I use trypsin as enzyme and '-ntt 2'.
The sequences of database all are tryptic peptides([^KR]*.), so I expect that all PSMs is '(pre=-,post=-)'. (at least first one)
However, I find a lot of PSMs which is '(pre=M,post=-)'.
By the way, it seem like methionine in start of sequence will be cleaved, but I am not sure.

java -jar MSGFPlus.jar -s test.mzML -d database.fasta -o test.mzid -t 20ppm -ti 0,1 -thread 8 -tasks 8 -tda 0 -m 1 -inst 1 -e 1 -protocol 5 -ntt 2 -minLength 6 -maxLength 40

Other problem is that when I use MSGFPlus to convert mzid to tsv, I find a result like below in tsv file, but it dose not match with sequences in the fasta file. However, when I use MzidToTsvConverter to do this, the same problem is not happen.

TSV from MSGFPlus:
(...) Peptide	Protein (...)
(...) LSAFQR	h0000666681(pre=-,post=-);h0001927668(pre=-,post=R) (...)

Fasta file:
\>h0000666681
LSAFQR
\>h0001927668
MLSAFQR

[test.zip](https://github.com/sangtaekim/msgfplus/files/1473778/test.zip)

**Comment by sangtaekim** [comment]
Sorry for the delay.  MS-GF+ is designed to consider the leading M cleavage even when '-ntt 2'. So it's a feature rather than a problem.

@FarmGeek4Life may be able to answer the second question.
