### ISSUE TITLE
Fragment mass tolerance using "Q-Exactive"

### ISSUE THREAD

**Issue by Matthias313** [MSGFPlus/msgfplus#17]
What is the default fragment mass tolerance when setting -instrument to "Q-Exactive"?

Thanks for any help
Matthias

**Comment by Matthias313** [comment]
Or were in the code is this information specified?
As far as I understood when choosing Q-Exactive "3 is used". 

    -inst InstrumentID (0: Low-res LCQ/LTQ (Default for CID and ETD), 1: High-res LTQ (Default for HCD), 2: TOF, 3: Q-Exactive)
        Identifier of the instrument to generate MS/MS spectra (used to determine the scoring model).
        For "hybrid" spectra with high-precision MS1 and low-precision MS2, use 0.
        For usual low-precision instruments (e.g. Thermo LTQ), use 0.
        If MS/MS fragment ion peaks are of high-precision (e.g. tolerance = 10ppm), use 2.
        For TOF instruments, use 2.
        For Q-Exactive HCD spectra, use 3.
        For other HCD spectra, use 1.

But what does this mean in ppm?

**Comment by alchemistmatt** [comment]
Although you can specify the precursor tolerance with `-t` you cannot specify the fragment ion tolerance.  The answer to your question is "It's complicated" -- the tolerance is determined automatically by the training algorithm and it will take some effort for us to dive into the code to determine the actual tolerance associated with the Q-Exactive HCD scoring parameters.

**Comment by Matthias313** [comment]
@alchemistmatt thank you for the fast response and all the information.
However, hence the mass tolerances (both on MS1 and MS2) have an influence on the search results, it would be interesting to actually know what fragment mass tolerance is used in MSGF+ when specifying the instrument to Q-Exactive.
Furthermore, for a comprehensive comparison of the influence of the mass tolerances in the different search engines it is necessary to adjust this parameter in all search engines. 

Have you had any luck, or would it be possible to dive into the code? =)
Best regards and many thanks!
Matthias
