### ISSUE TITLE
Unspecific cleavage: question

### ISSUE THREAD

**Issue by sgielis** [MSGFPlus/msgfplus#23]
Dear all,

I would like to use MS-GF+ for peptidomics studies. Since I start from a protein database, I need to apply the  'unspecific cleavage' setting.

However, I am wondering how MS-GF+ carries out this unspecific cleavage.
Does it give all possible peptides for every protein?

Best regards,

Sofie

**Comment by alchemistmatt** [comment]
Yes, for a given parent ion m/z, it will test all possible peptides (for every protein) whose monoisotopic mass matches the parent ion monoisotopic mass, within the specified tolerance.  You'll want to use `-e 0 -ntt 0`.  Given that this greatly expands the search space, the searches will be very slow if you have a big FASTA file (over ~10 MB)
