### ISSUE TITLE
'Warning: Illegal reflective access'

### ISSUE THREAD

**Issue by jspmccain** [MSGFPlus/msgfplus#26]
Hello,

I'm experiencing the following warning:

![image](https://user-images.githubusercontent.com/7434733/39496306-330ad154-4d74-11e8-9c37-f8e012042caa.png)

I'm not really sure how to interpret this? Any advice is appreciated!

Thanks,

Scott

**Comment by FarmGeek4Life** [comment]
Let me guess: you're using Java 9 to run MS-GF+? This is a known issue, and there is little I can do about it beyond wait for the maintainers of MS-GF+ dependencies to appropriately update their own dependencies.

This is also why the release notes for [Release v2018.01.83](https://github.com/MSGFPlus/msgfplus/releases/tag/v2018.01.30) have this line, and a remark on warnings:

Java 9 compatibility: add dependencies on com.sun.xml.bind:jaxb-impl and jaxb:activation to support use with Java 9 (with some warnings). Without this change, users must supply the Java VM argument "--add-modules=java.xml.bind,java.activation"

**Comment by jspmccain** [comment]
Yes that's exactly right, I'm using 'openjdk version "9.0.4".

I'm not entirely sure how you'd add those dependencies on com.sun.xml.bind:jaxb-impl and jaxb:activation ? If you have any guidelines or instructions for that they'd be greatly appreciated!

So if those dependencies are not added, I can supply the argument to the main command for using MSGF+?

Thank you!

**Comment by FarmGeek4Life** [comment]
Well, the "add dependencies" portion was a change to the code so that you could still run MS-GF+ with Java 9, without needing to add extra text to the command line. The "(with some warnings)" is a reference to the warnings you saw, because there are going to be some changes in those, and so they might be errors with Java 10 instead of just warnings.

**Comment by alchemistmatt** [comment]
Just a note, these warnings are still occurring with [Java 12](https://jdk.java.net/12/)
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/C:/DMS_Programs/MSGFDB/MSGFPlus.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
We don't have a fix for this, but I'm including these here for reference nonetheless.

**Comment by FarmGeek4Life** [comment]
Next release will have a fix for the warning messages (by depending on jaxb-runtime 2.3.1+ instead of jaxb-impl 2.2.7)
