### ISSUE TITLE
Suffix Creation: Java heap space Except in thread 'main' java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by jspmccain** [MSGFPlus/msgfplus#27]
I'm running MSGF+ and believe the suffix creation is running out of memory:

![image](https://user-images.githubusercontent.com/7434733/39499416-2b63679e-4d84-11e8-9bf3-ece45b5575b1.png)

The mzML file I'm using is 4.6GB, produced with an Orbitrap VelosPRO, and the protein database I'm searching on is 0.28GB. 

The command I ran is:

java -Xmx3500M -jar MSGFPlus.jar -s 180412_Rep_1.mzML -d assembly.orf.fasta -tda 1

If I don't use a target-decoy approach (ie -tda 0), then this memory issue does not appear.

I'm running 4.15.0-15-generic Ubuntu, with 64 CPUs, 2 threads per core, with 121GB available RAM. Any thoughts on how to fix this are greatly appreciated!

**Comment by FarmGeek4Life** [comment]
try changing -Xmx3500M to something like -Xmx16G

-Xmx is the heap space maximum allocation, and 3.5GB is apparently too small for creating that target/decoy suffix array.
