### ISSUE TITLE
With thermo fusion lumos, which codes should I use in instrument option?

### ISSUE THREAD

**Issue by TnakaNY** [MSGFPlus/msgfplus#35]
Hi,

I am going to analyze a data derived from Thermo Fusion Lumos by MSGF+.

In instrument code, MSGF+ has below; 
0: Low-res LCQ/LTQ (Default), 1: Orbitrap/FTICR, 2: TOF, 3: Q-Exactive

Which code should I use for Fusion Lumos data? 

Best,
TnakaNY

**Comment by alchemistmatt** [comment]
I agree, the difference between mode 1 (Orbitrap) and mode 3 (Q-Exactive) is a bit nebulous.  Likely the scoring model was trained with a different set of training data.  Most likely the Q-Exactive scoring model was trained with high res MS1 / high res MS2 datasets.  If your Fusion Lumos data is high/high, mode 3 is likely better.  If it is high res MS1 / low res MS2 (using the ion trap), then mode 1 is better.

Of course, it wouldn't hurt to try both modes with your data and see which gives more high confidence identifications.

**Comment by alchemistmatt** [comment]
Correction.  I just looked at my automation code and it uses the following logic:

- If the instrument is a QExactive, use mode 3
- If the instrument has HCD spectra (which should be high res MS2), use Mode 1
- If the instrument has high res MS2 spectra, use Mode 1
- If the instrument has low res MS2 spectra, use Mode 0

You can tell if the MS2 spectra are high res by looking for `FTMS` in the scan filter, for example `FTMS + p NSI`.  Low res spectra have `ITMS` in the scan filter.  Thus, for your Fusion Lumos data use mode 1.

**Comment by TnakaNY** [comment]
Hi,
Thank you for your quick reply!
I will change my instrumental code to 1 from 3.

Very best,
TnakaNY
