### ISSUE TITLE
PSMs matching to unique proteins

### ISSUE THREAD

**Issue by haripazhayath** [MSGFPlus/msgfplus#38]
I am using latest version of this software. Searched the mzml files using uniprot fasta.  Argument used is high precision. When mapped PSMs with protein annotations, all PSMs are mapping to unique proteins. No PSMs found are mapping to multiple proteins. Is this usual ?. Can somebody help me with this?

**Comment by alchemistmatt** [comment]
It depends on the software that you used to examine the results.  MSGF+ creates a .mzid file with the results, and that file definitely keeps track of all of the proteins that a given peptide is present in.  Most people convert that file to another format, often a tab-delimited file, and there are several tools for that.  What tool did you use?  I would advise using the Mzid-To-Tsv-Converter , which is available at https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/releases
When running that tool , use -unroll to assure that peptides that are in multiple proteins will have multiple rows in the output file (one row for each peptide/protein combo).  An example command line is shown at https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter

**Comment by haripazhayath** [comment]
I am using MSnbase, in which I combine mzid file with mzml file. I am not sure whether it uses -unroll feature.

**Comment by alchemistmatt** [comment]
I am not familiar with that tool (I see it's part of Bioconductor).  I suspect it's a limitation of MSnbase, but you'd have to contact the authors to confirm.  This page does mention that various filters are applied when the data is loaded
https://lgatto.github.io/MSnbase/reference/addIdentificationData-methods.html
and it's very likely that the .mzid reader code is only keeping the first protein name listed in the .mzid file.

**Comment by haripazhayath** [comment]
Thank you very much for the reply. I will confirm with the author. Can you please tell me the other tools which can be used for quantification of ITRAQ data? .Basically I need to combine mzid with Spectra labels.

**Comment by alchemistmatt** [comment]
In our group we extract the reporter ions using [MASIC](https://github.com/PNNL-Comp-Mass-Spec/MASIC/releases).  You can then link up the MASIC results with the MSGF+ results using the [MASIC Results Merger](https://github.com/PNNL-Comp-Mass-Spec/MASIC-Results-Merger/releases) (see the [Readme](https://github.com/PNNL-Comp-Mass-Spec/MASIC-Results-Merger)).  I'm sure there are other tools available, but I'm not familiar with them.

**Comment by haripazhayath** [comment]
Thank you

HARI
