### ISSUE TITLE
Peptide Matches Per Spectrum

### ISSUE THREAD

**Issue by wong15w** [MSGFPlus/msgfplus#40]
I was looking through the tsv file and noticed that in some cases, with default settings, it was possible to find one spectra being assigned to multiple peptide interpretations. I also noticed that the peptides had the same score and was wondering what the tie breaking procedure was for these cases where multiple peptides can be assigned to the same spectra when those peptides have the same score. I was under the impression that the default behavior was that only 1 peptide match would be reported per spectrum.  Is this the intended behavior?

**Comment by alchemistmatt** [comment]
Yes, the default behavior is to report the highest scoring peptide for each spectrum.  In the case when two peptides have the exact same score, both are reported.  MS-GF+ does not have a tie-breaking mechanism -- this is something you would have to decide how to handle.  Personally, I'd keep both identifications and allow them to be evidence for both proteins, but that's the optimistic view.  The pessimistic view would be to ignore both peptides.  The other option is to manually inspect the spectrum and make the call yourself.

**Comment by adder** [comment]
Hey
I have a question related to this.
Sometimes you see a spectrum that is assigned to different PSMs with the same score with the same rank (eg, all rank 1) and sometimes with different ranks (rank 1 ,2, 3,4).
Why is this?
what are the rules that decides if something gets the same rank or a different rank.

Best regards

**Comment by FarmGeek4Life** [comment]
The mzIdentML specification says the following about the rank:

> For an MS/MS result set, this is the rank of the identification quality as scored by the search engine. 1 is the top rank. If multiple identifications have the same top score, they should all be assigned rank =1. For PMF data, the rank attribute may be meaningless and values of rank = 0 should be given. 

So, if the PSMs are for the same spectrum and have the same score, they are supposed to have the same rank; however, MS-GF+ currently ignores this part of the requirement, and instead gives each PSM a different rank.

**Comment by adder** [comment]
Thanks for the answer.
I did some further investigation to see why I found PSMs with the same score and same rank.

I belief if the different PSMs have the same score and same sequence but originate from different proteins, they get the same rank.
If havethey the same score but different sequence (eg. I -> L) the get another rank.

**Comment by FarmGeek4Life** [comment]
For a converted mzid file, that would be mostly correct with the current implementation. A rank is given to a peptide+mods-to-spectrum match, and that peptide can occur in multiple proteins.
So, in the mzid file you might see results for a single spectrum like:
```
spec5:
PEPTC+57CIDE rank 1: protein1, protein2, protein3
PEPTCC+57IDE rank 2: protein1, protein2, protein3
```
The unrolled tsv file would then have something like:
```
spec5   protein1   PEPTC+57CIDE   rank1
spec5   protein2   PEPTC+57CIDE   rank1
spec5   protein3   PEPTC+57CIDE   rank1
spec5   protein1   PEPTCC+57IDE   rank2
spec5   protein2   PEPTCC+57IDE   rank2
spec5   protein3   PEPTCC+57IDE   rank2
```

I do have code changes I need to test that will change the rank numbers to be in compliance with the specification.

**Comment by adder** [comment]
Thanks for the clarification!
