### ISSUE TITLE
Make user can specify where BuildSA generate files

### ISSUE THREAD

**Issue by hsiaoyi0504** [MSGFPlus/msgfplus#47]
It would be good if user can specify where BuildSA generate files. Or user may not have permission to creating files in the same path. (User can still do that but he/she would need to copy the fasta file).

**Comment by hsiaoyi0504** [comment]
My colleague just found that it works with `-o` option, but it seems to me that help message of this part is commented out https://github.com/MSGFPlus/msgfplus/blob/cd212b0c2165d21a38213c67b67b6ed8f5b2f93d/src/main/java/edu/ucsd/msjava/msdbsearch/BuildSA.java#L47.

**Comment by alchemistmatt** [comment]
Good find.  I have updated the documentation and the syntax shown at the command line to mention 
`-o OutputDir`
I also added validation code to provide clear messages when the output directory cannot be created or is not writable. The new release is at https://github.com/MSGFPlus/msgfplus/releases

**Comment by alchemistmatt** [comment]
Good find.  I have updated the documentation and the syntax shown at the command line to mention 
`-o OutputDir`
I also added validation code to provide clear messages when the output directory cannot be created or is not writable. The new release is at https://github.com/MSGFPlus/msgfplus/releases

**Comment by hsiaoyi0504** [comment]
Thanks.
