### ISSUE TITLE
RTINSECONDS does not seem to be parsed from MGF input file

### ISSUE THREAD

**Issue by arnscott** [MSGFPlus/msgfplus#50]
When parsing an MGF file using the MgfSpectrumParser.java, certain embedded search parameters are hardcoded (CHARGE, TITLE, SEQ, PEPMASS, etc.) but not RTINSECONDS. So the SpectrumIdentificationResults returned don't have the usual cvParam 'scan start time'. This scan start time is reported when using mzML (I can see it being parsed in MzXMLSpectraMap) files as the input, but does not seem to be the case with MGF files. The Spectrum class is already able to accommodate the retention time, so it seems like it could just be adding another clause to the conditional of the MGF embedded parameter parser. I was wondering if there was a specific reason that RTINSECONDS is skipped over in the MGF parser that I was missing (It could very well be)? However, it would be extremely useful for the scan start time to be available in the results if it is provided as an embedded search parameter in the MGF input file.

**Comment by FarmGeek4Life** [comment]
The focus was supporting it in mzML, since that is what we primarily use here; also, at the time I added the "scan start time" output to the mzid, I was working on MzRefinery, and focused on mzML for that as well. So, there isn't a specific reason for it to be skipped over, beyond being an "incomplete implementation" for reading and outputting the scan start times.

**Comment by alchemistmatt** [comment]
I have implemented parsing RTINSECONDS from .mgf files (63d94e69).  I also added logic to parse out the scan number from the TITLE line (c9dbda31), if the TITLE line is of the form `DatasetName.ScanStart.ScanEnd.Charge` which is the form written by msconvert (from ProteoWizard). See release v2018.10.15 at https://github.com/MSGFPlus/msgfplus/releases/tag/v2018.10.15
