### ISSUE TITLE
MSGF+ Training parameter location

### ISSUE THREAD

**Issue by mrForce** [MSGFPlus/msgfplus#56]
I trained a param file using ScoringParamGen. The documentation says to place the param file (in my case, named HCD_QExactive_NoCleavage_Automatic.param) into a folder called "params". Should this folder by placed in the MSGF+ installation (in the same directory as MSGFPlus.jar), or in the directory that the search is being ran from? 

Additionally, if I'm trying to train on a search done with "-e 0" (unspecific cleavage), what enzyme should I use for ScoringParamGen?

**Comment by FarmGeek4Life** [comment]
The folder should go in the working directory, i.e. the directory the command line says you are currently in before you enter 'java -Xmx... -jar MSGFPlus.jar ...'

**Comment by mrForce** [comment]
Perfect, thanks. I really appreciate you guys answering my questions. Though what should I do if I want to train params on a search done with unspecific cleavage?
