### ISSUE TITLE
Config file neeed

### ISSUE THREAD

**Issue by ypriverol** [MSGFPlus/msgfplus#57]
Dear @alchemistmatt @FarmGeek4Life: 

Moving towards integration of MSGF+ with other systems would be great to have a parameters file for all MSGF+ parameters.(perhaps excluding in file and output file). do you think that is possible, are you accepting PR around that?

**Comment by alchemistmatt** [comment]
We would definitely accept a pull request for that.  Regarding the parameter file format, we already have one that we use internally, so if you could adopt that format it would be a win for us too.  Our internal system (C# code base) reads the parameter file and converts the settings to the command line arguments.  Having Java code inside MS-GF+ read the parameter file would be an improvement.  See these links for some example parameter files.

* [MSGFDB_Tryp_DynMetOx_TMTExclusive_K_Acetyl_Stat_CysAlk_TMT_6Plex_20ppmParTol.txt](https://github.com/MSGFPlus/msgfplus/files/2822637/MSGFDB_Tryp_DynMetOx_TMTExclusive_K_Acetyl_Stat_CysAlk_TMT_6Plex_20ppmParTol.txt)
* [MSGFDB_Tryp_DynSTYPhos_Stat_CysAlk_iTRAQ_4Plex_10ppmParTol.txt](https://github.com/MSGFPlus/msgfplus/files/2822638/MSGFDB_Tryp_DynSTYPhos_Stat_CysAlk_iTRAQ_4Plex_10ppmParTol.txt)
* [MSGFDB_PartTryp_Dyn_MetOx_CysAlk_20ppmParTol.txt](https://github.com/MSGFPlus/msgfplus/files/2822639/MSGFDB_PartTryp_Dyn_MetOx_CysAlk_20ppmParTol.txt)

The code also converts the dynamic and static mods specified in the parameter file to create a file like MSGFPlus_Mods.txt (next bullet).  However, for the new code you're proposing, this file shouldn't need to be created; just load the mod info into memory when reading the parameter file.
* [MSGFPlus_Mods.txt](https://github.com/MSGFPlus/msgfplus/files/2822657/MSGFPlus_Mods.txt)

For reference, the C# code that parses these parameter files is at 
https://github.com/PNNL-Comp-Mass-Spec/DMS-Analysis-Manager/blob/master/Plugins/AM_MSGFDB_PlugIn/clsMSGFPlusUtils.cs#L2079
using this mapping:
https://github.com/PNNL-Comp-Mass-Spec/DMS-Analysis-Manager/blob/master/Plugins/AM_MSGFDB_PlugIn/clsMSGFPlusUtils.cs#L1133

**Comment by ypriverol** [comment]
I think it make sense to provide a config file that contains also the modifications in the same format they were provided before but only one file. Working with your examples now.

**Comment by ypriverol** [comment]
First implementation provided in the following PR https://github.com/MSGFPlus/msgfplus/pull/59

**Comment by ypriverol** [comment]
The PR has been integrated and the current version of MSGF+ support config files. I will close this Issue.
