### ISSUE TITLE
Preferred way of analyzing mzid files

### ISSUE THREAD

**Issue by tivdnbos** [MSGFPlus/msgfplus#65]
Hi,

I was wondering what the preferred way is to analyze .mzid files on a linux machine, meaning, given a certain FDR, get a list of spectra and the identified peptide sequences back.
I tried MzidToTsvConvertor, but the output generates a 0 for all q-values. Any idea what can cause this?

Best wishes.

**Comment by FarmGeek4Life** [comment]
Well, the MzidToTsvConverter just outputs whatever values are in the mzid file. If all of the q-values are zero, then they were all reported as '0' in the mzid file.

**Comment by alchemistmatt** [comment]
MzidToTsvConverter is the correct tool to use.  Try a less strict filter threshold and you should start to see non-zero Q-values.  Note, though, for Q-values to be computed properly, you need to let MS-GF+ create the decoy FASTA file, and decoy proteins will need to be preceded by XXX_

**Comment by tivdnbos** [comment]
Thanks! I searched a concatenated target-decoy database (with the XXX_ prefix), but with -tda 0. With the target db only and -tda 1 it worked.
