### ISSUE TITLE
Suffix instead of Prefix pattern for decoys

### ISSUE THREAD

**Issue by tivdnbos** [MSGFPlus/msgfplus#66]
Hi all,

I was wondering if there's a possibility to use suffix patterns instead of prefix patterns with MS-GF+? And, if not, if there's a way to implement this in the code?

Best wishes,

**Comment by sangtaekim** [comment]
It's conceptually not difficult but will require code changes. I believe we don't have a plan to change it unless there's a strong need. If you're interested in changing it yourself, https://github.com/MSGFPlus/msgfplus/blob/master/src/main/java/edu/ucsd/msjava/msdbsearch/SuffixArrayForMSGFDB.java will be a good start.

**Comment by FarmGeek4Life** [comment]
Another option to effectively change the prefix to a suffix is by using a regular expression search and replace tool on the mzid.

One example that will work on a linux command line:
`sed -i 's/\(accession="\)XXX_\([^"]\+\)/\1\2_REVERSED/g' test.mzid`
XXX_ and _REVERSED can be changed to whatever they need to be.

**Comment by tivdnbos** [comment]
Thanks! I was able to fix it.

Best wishes,
Tim
