### ISSUE TITLE
Peptide Q-value less than PSM Q-value?

### ISSUE THREAD

**Issue by mrForce** [MSGFPlus/msgfplus#67]
Hi,

I've ran searches against several datasets with TDC, and frequently, the PSM Q-Value is greater than the Peptide Q-Value. If I filter by MS-GF:PepQValue (at a cutoff of 0.05), I consistently get more identifications than if I filter by MS-GF:QValue. However, I also get fewer unique peptides if I filter by MS-GF:PepQValue than if I filter by MS-GF:QValue. 

While it's plausible that this could happen occasionally, I'm a little concerned about the fact that it occurs consistently across 8 different data-sets. Should I be?

**Comment by alchemistmatt** [comment]
That's likely just how the math is working out.  Open Excel file [QValue_Computation_Excerpt.xlsx](https://github.com/MSGFPlus/msgfplus/files/3357217/QValue_Computation_Excerpt.xlsx) to see how Q-Value is calculated.  Compare column `QValue` to `Manually computed Qvalue` and examine the formulas.  Note that all PSMs with the same value for `Reverse PSMs` are assigned the same Q Value.

You'd use this same approach to manually compute PepQValue, starting with a list of unique peptides, using the best score (smallest `SpecEValue`) for each unique peptide.  Note that this Excel file is an excerpt of the original data, to keep the file size smaller.  Thus, the formulas in column R (`ResultID`) are replaced with integers starting in row 107.  If you use this spreadsheet with your own data, be sure to fill down the formulas to all rows in column R.  If you don't have Excel, you can open this file with LibreOffice Calc (among other programs).

**Comment by mrForce** [comment]
Ah, okay, thanks.
