### ISSUE TITLE
(Question) Quantitative output

### ISSUE THREAD

**Issue by meilumcdermott** [MSGFPlus/msgfplus#69]
After running data with the TMT protocol, I do not have quantitative output. I am assuming that MSGF+ does not output quantification results? What other programs or methods are suggested to use with MSGF+ to get quantification data (eg TMT6plex)? Thanks!

**Comment by alchemistmatt** [comment]
Correct, MS-GF+ does not quantify TMT reporter ions.  We use MASIC, which is available at https://github.com/PNNL-Comp-Mass-Spec/MASIC/releases

That is a Windows application, but it supports command line parameters, allowing it to be run from a batch file.   I also have a console version of MASIC that is Linux compatible, including reading both Thermo .Raw files and .mzML files.   I am still testing its functionality and working out some issues, but I hope to have it released this week.  The new version will be available at https://github.com/PNNL-Comp-Mass-Spec/MASIC/releases

**Comment by alchemistmatt** [comment]
A related application is https://github.com/PNNL-Comp-Mass-Spec/MASIC-Results-Merger which can combine the results from MS-GF+ and MASIC to create a single file with both sets of data, linked up by scan number.  For details, see the MASIC-Results-Merger Readme

**Comment by meilumcdermott** [comment]
Thanks for your answer!
