### ISSUE TITLE
-maxMissedCleavages not showing in mzIdentML

### ISSUE THREAD

**Issue by detritus** [MSGFPlus/msgfplus#72]
Tested in: Release (v2019.07.03)

When specifying -maxMissedCleavages 1, the value is not being output in the mzIdentML:

Actual:
`      <Enzyme semiSpecific="false" missedCleavages="1000" id="Tryp">`
Expected:
`      <Enzyme semiSpecific="false" missedCleavages="1" id="Tryp">`

From a glance at the data, it seems the value set is being used, it is only the the missedCleavage attribute that is not being written correctly.

**Comment by FarmGeek4Life** [comment]
Well, [this line](https://github.com/MSGFPlus/msgfplus/blob/master/src/main/java/edu/ucsd/msjava/mzid/AnalysisProtocolCollectionGen.java#L133) says you are probably 100% correct.

**Comment by FarmGeek4Life** [comment]
Commit c7fd191 is a fix for this, so the next release will resolve this issue.

**Comment by detritus** [comment]
Thanks @FarmGeek4Life. Glad to know the issue is only cosmetic. :)
