### ISSUE TITLE
Read many input mgf files at one time

### ISSUE THREAD

**Issue by dengchuanbio** [MSGFPlus/msgfplus#73]
Hi, i am a newbie to use the great msgfplus, but I ran into a little trouble. since i have a lot of mgf files, to search it, i need use `java -jar xxx` many times in a bash script, so does there have any way/settings to put/configure those input files into some where so i just need only one statement run it all at one time?

**Comment by FarmGeek4Life** [comment]
If you provide the path to a folder containing the files you want to search (they cannot be in subfolders), MS-GF+ will search all of the files in that folder with the same settings (but not in parallel).

**Comment by dengchuanbio** [comment]
thx, besides it would be nice to be able to run it in parallel

**Comment by dengchuanbio** [comment]
thx, besides it would be nice to be able to run it in parallel
