### ISSUE TITLE
use non-0 exit code on failure

### ISSUE THREAD

**Issue by cbielow** [MSGFPlus/msgfplus#75]
when running MSFG+ with invalid arguments, e.g.
```
java.exe -Xmx3500m -jar C:/Users/bielow/Downloads/MSGFPlus_v20190703/MSGFPlus.jar -s C:\TEMP\RAW\TMT_ch_19Jan2017_SM-1-1_Sp-6-2_HCD-OT-MS2_1.mzML.gz -o msgfplus_output.mzid -d c:\TEMP\fasta\uniprot-SP_human.fasta -t 10ppm -ti 0,1 -tda 0 -m 0 -inst 0 -e 1 -protocol 0 -ntt 2 -minLength 6 -maxLength 40 -minCharge 2 -maxCharge 3 -n 1 -addFeatures 1 -thread 11 -mod msgfplus_mods.txt

...

[Error] Invalid value for parameter -s: C:\TEMP\RAW\TMT_ch_19Jan2017_SM-1-1_Sp-6-2_HCD-OT-MS2_1.mzML.gz
        (extension does not match a known file type: .mzML, .mzXML, .mgf, .ms2, .pkl, _dta.txt)
```

the exit code reported by MSGF+ is `0`, i.e. success.
This is very unfortunate for automated pipelines, which now expect the result files to be present.
Even worse, usually, the stdout/stderr of MSGF+ is omitted on success and the user does not know what went wrong.

FIX: please use a non-0 exit code when an error occurs.

affected MSGF+ releases: 20190703 and earlier

**Comment by FarmGeek4Life** [comment]
Commit 2d2cc63 fixes this error (return -1 when there is a parameter error).

**Comment by cbielow** [comment]
thanks!
