### ISSUE TITLE
Add a maximum allowed missed cleavages option?

### ISSUE THREAD

**Issue by fcyu** [MSGFPlus/msgfplus#9]

**Comment by lars20070** [comment]
+1

**Comment by oliverschilling** [comment]
+1

**Comment by JB-MS** [comment]
+1

That would be a nice improvement!

**Comment by kernursula** [comment]
A maximum missed cleavage option would be crucial for the analysis of samples that were digested seperately, such as label free samples

**Comment by Stortebecker** [comment]
> maximum allowed missed cleavages

Is MSGFPlus currently searching for peptides with missed cleavage when using default settings?

**Comment by kernursula** [comment]
Yes. As many as there are. You can not specify the number of missed cleavages. Therefore we asked a developer to implement a new section in IDFilter to filter for a certain range of missed cleavages. this section is only available with the developers version of OMS.
Ursula


 

    Am Mittwoch, 22. November 2017, 11:40:21 MEZ hat Florian Christoph Sigloch <notifications@github.com> Folgendes geschrieben:  
 
 

maximum allowed missed cleavages


Is MSGFPlus currently searching for peptides with missed cleavage when using default settings?

**Comment by FarmGeek4Life** [comment]
Any of you are welcome to make a pull request that adds such a change.

**Comment by lars20070** [comment]
Resolved in PR #37.
@CWRU-CPB Thanks a lot for this new feature!

**Comment by CWRU-CPB** [comment]
No problem @lars20070. I hope it's useful!

**Comment by alchemistmatt** [comment]
This functionality is included in Release v2018.06.28
https://github.com/MSGFPlus/msgfplus/releases/

Use `-maxMissedCleavages` as described [in the documentation](https://htmlpreview.github.io/?https://raw.githubusercontent.com/MSGFPlus/msgfplus/master/doc/MSGFPlus.html)

I will admit that I have not yet tested this, but @CWRU-CPB did some extensive testing.  Getting feeding from others on the new feature would be appreciated.
